Building DAG of jobs...
Full Traceback (most recent call last):
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/io.py", line 794, in expand
    for filepattern in filepatterns
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/io.py", line 795, in <listcomp>
    for comb in map(dict, combinator(*flatten(wildcards[filepattern])))]
KeyError: 'datasetgeneration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/rules.py", line 548, in apply_input_function
    value = func(Wildcards(fromdict=wildcards), **_aux_params)
  File "/Users/morril01/Documents/PhD/GlobalDA/code/Snakefile", line 460, in <lambda>
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/io.py", line 797, in expand
    raise WildcardError("No values given for wildcard {}.".format(e))
snakemake.exceptions.WildcardError: No values given for wildcard 'datasetgeneration'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/__init__.py", line 544, in snakemake
    export_cwl=export_cwl)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/workflow.py", line 421, in execute
    dag.init()
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 122, in init
    job = self.update([job], progress=progress)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 600, in update
    progress=progress)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 648, in update_
    job).items()
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 1164, in collect_potential_dependencies
    jobs = file2jobs(file)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 1257, in file2jobs
    raise exceptions[0]
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 1252, in file2jobs
    jobs.append(self.new_job(rule, targetfile=targetfile))
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/dag.py", line 1047, in new_job
    format_wildcards=format_wildcards, targetfile=targetfile)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/jobs.py", line 96, in __init__
    self.input, input_mapping, self.dependencies = self.rule.expand_input(self.wildcards_dict)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/rules.py", line 647, in expand_input
    incomplete_checkpoint_func=handle_incomplete_checkpoint)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/rules.py", line 579, in _apply_wildcards
    **aux_params)
  File "/Users/morril01/anaconda3/envs/snakemake-globalDA/lib/python3.6/site-packages/snakemake/rules.py", line 552, in apply_input_function
    raise InputFunctionException(e, rule=self, wildcards=wildcards)
snakemake.exceptions.InputFunctionException: WildcardError: No values given for wildcard 'datasetgeneration'.
Wildcards:
datasetgeneration=GenerationK

InputFunctionException in line 338 of /Users/morril01/Documents/PhD/GlobalDA/code/Snakefile:
WildcardError: No values given for wildcard 'datasetgeneration'.
Wildcards:
datasetgeneration=GenerationK
